Add Bidog info and log
TP-Lab/tokens pull request #3952
Opened 2021-11-06 08:25 UTC by Binancedogofficial

3000 TPT transfer address

2021-11-11 23:02 UTC, Bidogofficial commented on bsc/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/info.json
> + "explorer": "https://bscscan.com/address/0x265f638eab14dd43d80bb71aae3289b1c6d46a3f",
"explorer": "https://bscscan.com/address/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f",

2021-11-11 23:06 UTC, Bidogofficial commented
Sorry I forget to transfer it into Checksum address I have change it in reviewer please accept it

2021-11-11 23:08 UTC, Bidogofficial requested changes

2021-11-11 23:08 UTC, Bidogofficial commented on bsc/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/info.json
> + "explorer": "https://bscscan.com/address/0x265f638eab14dd43d80bb71aae3289b1c6d46a3f",
"explorer": "https://bscscan.com/address/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f",

2021-11-11 23:08 UTC, Bidogofficial commented on bsc/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/info.json
> + "description": "🐶Binance dog 🐶is a deflationary token which is centered by the community and driven by the internal force.
"description": "🐶Binance dog 🐶is a deflationary token which is centered by the community and driven by the internal force.",

2021-11-11 23:08 UTC, Bidogofficial commented on bsc/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/info.json
> +",
delete

2021-11-11 23:08 UTC, Bidogofficial commented on bsc/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/info.json
> + "id": "0x265f638eab14dd43d80bb71aae3289b1c6d46a3f"
"id": "0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f"

2021-11-18 08:03 UTC, guoxintongsam commented
Please refer to the tutorial, and re-submit your files in the correct format. Please submit your logo in the correct size.

2021-11-18 08:03 UTC, closed without merging

2022-01-03 06:37 UTC, jiasutijiao commented
专业提交logo！审核失败的走加速审核小时内包过！价格显示问题！QQ:3579750034